print("hello world")
name=input("enter your name:")
print(name)
age=input("enter your age:")
print(age)
gender=input("enter your gender:")
print(gender)
address=input("enter your address:")
print(address)
height=input("enter your height:")
print(height)
color=input("enter your color:")
print(color)